# Generated by Django 3.1.3 on 2020-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblcommonmasters',
            fields=[
                ('autoid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isactive', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('otherfield', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbloptions',
            fields=[
                ('optionid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=550, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('alternet_number', models.CharField(max_length=16)),
                ('facebook_link', models.CharField(max_length=300)),
                ('twitter_link', models.CharField(max_length=300)),
                ('youtube_link', models.CharField(max_length=300)),
                ('instagram_link', models.CharField(max_length=300)),
                ('linkedin_link', models.CharField(max_length=300)),
                ('github_link', models.CharField(max_length=300, null=True)),
                ('google_ver_id', models.CharField(blank=True, max_length=50, null=True)),
                ('googleana_script', models.TextField(blank=True, null=True)),
                ('facebook_script', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=150, null=True)),
                ('favicon', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
